[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch]

[project]
name = "mesoscopy"
description = "Analysis pipeline for rodent widefield calcium imaging data."
readme = "README.md"
requires-python = ">=3.12"
license = {file = "LICENSE"}
authors = [
  { name = "Constantinos Eleftheriou", email = "Constantinos.Eleftheriou@ed.ac.uk" },
]
classifiers = [
    "Development Status :: 2 - Pre-Alpha",
    "Topic :: Scientific/Engineering",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3.12",
]
keywords = ["widefield", "imaging", "behaviour", "neuroscience"]
dependencies = [
    "Click", 
    "dask>=2021.4.1", 
    "dask-image>=2021.12.0", 
    "numpy>=1.21.2", 
    "h5py>=3.6.0", 
    "matplotlib", 
    "tables", 
    "graphviz", 
    "scipy>=1.7.1", 
    "zarr>=2.11.3", 
    "xmltodict", 
    "scikit-image", 
    "pandas", 
    "pynwb>=2.3.1",
    "napari[all]>=0.4.19"
]
dynamic = ["version"]

[project.urls]
Issues = "https://github.com/DuguidLab/mesoscopy/issues"
Source = "https://github.com/DuguidLab/mesoscopy"

[project.scripts]
mesoscopy = "mesoscopy:cli"

[tool.hatch.build.targets.wheel]
packages = ["src/mesoscopy"]

[tool.hatch.build.targets.sdist]
exclude = [
  "/.github",
  "/docs",
  "/exploratory",
]

[tool.hatch.version]
path = "src/mesoscopy/__about__.py"

[tool.hatch.envs.default]
python = "3.12"
path = ".hatch"

[tool.hatch.envs.test]
dependencies = [
  "coverage[toml]",
  "pytest",
  "pytest-cov",
  "pytest-mock",
]

[tool.hatch.envs.test.scripts]
run-coverage = "pytest --cov-config=pyproject.toml --cov=mesoscopy --cov=tests --cov-report=lcov:lcov.info"
run = "run-coverage --no-cov"

[tool.hatch.envs.style]
detached = true
python = "3.12"
dependencies = [
  "black",
  "pylint",
  "isort"
]

[tool.hatch.envs.style.scripts]
check = [
  "black --check --diff .",
  "isort --check-only --diff .",
]
fmt = [
  "isort .",
  "black .",
  "check",
]

[tool.hatch.envs.docs]
dependencies = [
  "mkdocs",
  "mkdocs-material",
  "mkdocstrings-python",
  "pymdown-extensions",
  "material-plausible-plugin",
]

[tool.hatch.envs.docs.scripts]
build = "mkdocs build --clean --strict"
serve = "mkdocs serve --dev-addr localhost:8000"
deploy = "mkdocs gh-deploy --force"

[tool.hatch.envs.typing]
dependencies = [
  "mypy>=1.0.0",
]

[tool.hatch.envs.typing.scripts]
check = "mypy --install-types --non-interactive src/mesoscopy tests"

[tool.mypy]
ignore_missing_imports = true
plugins = "numpy.typing.mypy_plugin"
disallow_untyped_defs = false
disallow_incomplete_defs = false
follow_imports = "normal"
pretty = true
show_column_numbers = true
show_error_codes = true
warn_no_return = false
warn_unused_ignores = true
